const auditSteps=[
  {kicker:'Step 1 · Your details',title:'Before we begin, tell us who this is for.',description:'We’ll use these details to personalise your workflow guidance.',contact:true},
  {kicker:'Step 1 · The context',title:'Tell us a little about your business.',description:'Choose the option that best describes the work you do today.',options:['Services & consulting','Creative or media','Retail & e-commerce','Health & wellness','Technology or SaaS','Something else']},
  {kicker:'Step 2 · The friction',title:'Where does work feel more manual than it should?',description:'Pick the workflow that currently creates the most drag.',options:['Capturing and following up with leads','Client onboarding and delivery','Booking, reminders and meetings','Content and social media','Reporting, admin or data entry','Team and customer communication']},
  {kicker:'Step 3 · The process',title:'How clear is that process today?',description:'There is no perfect answer. This helps us recommend a starting point that fits where you are now.',options:['It mostly lives in my head','It changes each time','It is repeatable, but not documented','It is documented and mostly consistent']},
  {kicker:'Step 4 · The rhythm',title:'How often does this work happen?',description:'The more often a task repeats, the more valuable a clear system can become.',options:['A few times a month','Every week','Most days','Many times a day']},
  {kicker:'Step 5 · Your tools',title:'Where does important work live?',description:'Select every tool or place that holds information for this workflow.',multi:true,options:['Google Workspace or Gmail','Microsoft 365 or Outlook','Notion','A CRM','A project management tool','Airtable or spreadsheet','Mostly email and notes']},
  {kicker:'Step 6 · The capacity',title:'How is the work shared right now?',description:'This helps us recommend a system that suits your capacity, not an idealised version of your business.',options:['It’s mostly just me','A small team of 2–5','A growing team of 6–20','A larger team with several functions']},
  {kicker:'Step 7 · The outcome',title:'What would a better workflow make possible?',description:'Choose the result that would make the biggest difference over the next 90 days.',options:['More time for higher-value work','Faster replies and fewer lost leads','A calmer, more reliable team rhythm','A clearer process I can delegate','Confidence in where to invest next']}
];

const recommendations={
  'Capturing and following up with leads':{title:'Build a <em>lead-response system.</em>',summary:'Your strongest first win is making sure every enquiry reaches the right place and receives a timely, consistent response.',first:'Capture every enquiry once',firstDetail:'Send website forms and inbox enquiries to one shared lead record automatically.',second:'Create a simple follow-up rhythm',secondDetail:'Set clear ownership, reminders and a first-response template so warm leads are never left waiting.'},
  'Client onboarding and delivery':{title:'Create a calmer <em>client handover.</em>',summary:'Your best next step is turning the repeatable parts of delivery into a reliable client journey your team can follow.',first:'Map the client journey',firstDetail:'List the handoffs from signed proposal to delivery, including what the client needs at each point.',second:'Automate the welcome sequence',secondDetail:'Trigger the right tasks, documents and updates as soon as a new client says yes.'},
  'Booking, reminders and meetings':{title:'Make booking <em>run itself.</em>',summary:'Your biggest opportunity is removing back-and-forth from booking while helping every meeting start better prepared.',first:'Give people one clear way to book',firstDetail:'Connect availability to a booking flow that asks the right questions upfront.',second:'Automate the meeting rhythm',secondDetail:'Send confirmations, reminders and internal preparation tasks without chasing calendars.'},
  'Content and social media':{title:'Build a repeatable <em>content rhythm.</em>',summary:'Your next best system is one that turns ideas into planned, approved and published content without losing the thread.',first:'Create one content pipeline',firstDetail:'Move ideas, drafts, approvals and publishing dates into a simple shared view.',second:'Set the handoffs',secondDetail:'Use clear owners and lightweight reminders so content keeps moving without constant check-ins.'},
  'Reporting, admin or data entry':{title:'Remove the <em>manual drag.</em>',summary:'Your best place to start is the repeat work that is being copied between tools, spreadsheets and people.',first:'Choose one repetitive task',firstDetail:'Pick the task that happens most often and takes the most attention to complete manually.',second:'Standardise, then connect',secondDetail:'Define the fields and approvals first, then link the tools so information only needs to be entered once.'},
  'Team and customer communication':{title:'Give every update a <em>clear home.</em>',summary:'The most valuable next step is making it obvious where conversations belong, who responds and what happens next.',first:'Separate urgent from routine',firstDetail:'Decide which messages need a real-time response and which can move through a shared workflow.',second:'Create visible ownership',secondDetail:'Use simple routing and reminders so customers and teammates do not have to ask twice.'}
};
const productRecommendations={
  'Capturing and following up with leads':{name:'Website Lead Capture & Follow-Up',price:'€49',url:'workflow-lead-capture.html'},
  'Booking, reminders and meetings':{name:'Discovery Call Booking System',price:'€69',url:'workflow-booking.html'},
  'Team and customer communication':{name:'Automated Sales Follow-Up',price:'€69',url:'workflow-follow-up.html'},
  'Content and social media':{name:'Automated Sales Follow-Up',price:'€69',url:'workflow-follow-up.html'}
};

const state={current:0,answers:[],contact:{firstName:'',lastName:'',company:'',website:'',email:''}};
const area=document.querySelector('#question-area'),nextButton=document.querySelector('#next-button'),previousButton=document.querySelector('#previous-button'),headerStep=document.querySelector('#header-step'),questionKicker=document.querySelector('#question-kicker'),questionCount=document.querySelector('#question-count'),headerProgress=document.querySelector('.audit-header-progress i'),totalSteps=auditSteps.length;
function isAnswered(step){if(step.contact){const c=state.contact;return Boolean(c.firstName.trim()&&c.lastName.trim()&&c.company.trim()&&c.website.trim()&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(c.email.trim()))}return step.multi?Array.isArray(state.answers[state.current])&&state.answers[state.current].length>0:Boolean(state.answers[state.current])}
function renderStep(){const step=auditSteps[state.current],answer=state.answers[state.current];questionKicker.textContent=step.kicker;questionCount.textContent=String(state.current+1).padStart(2,'0')+' / '+String(totalSteps).padStart(2,'0');headerStep.textContent='Step '+(state.current+1)+' of '+totalSteps;headerProgress.style.width=((state.current+1)/totalSteps)*100+'%';if(step.contact){const c=state.contact;area.innerHTML='<h2>'+step.title+'</h2><p class="question-description">'+step.description+'</p><div class="contact-grid"><label>First name<input data-contact="firstName" type="text" autocomplete="given-name" required value="'+c.firstName+'"></label><label>Last name<input data-contact="lastName" type="text" autocomplete="family-name" required value="'+c.lastName+'"></label><label>Company name<input data-contact="company" type="text" autocomplete="organization" required value="'+c.company+'"></label><label>Website<input data-contact="website" type="url" autocomplete="url" placeholder="https://yourcompany.com" required value="'+c.website+'"></label><label class="contact-email">Professional email<input data-contact="email" type="email" autocomplete="email" placeholder="you@company.com" required value="'+c.email+'"></label></div>';nextButton.disabled=!isAnswered(step);nextButton.innerHTML='Start my audit <span>→</span>';previousButton.disabled=true;return}let choices='';step.options.forEach((option,index)=>{const selected=step.multi?Array.isArray(answer)&&answer.includes(option):answer===option;choices+='<button class="choice'+(selected?' selected':'')+'" type="button" data-answer="'+option+'"><span>'+String(index+1).padStart(2,'0')+'</span>'+option+'<b>'+(step.multi?(selected?'✓':'+'):'→')+'</b></button>'});area.innerHTML='<h2>'+step.title+'</h2><p class="question-description">'+step.description+'</p>'+(step.multi?'<p class="choice-hint">Select all that apply</p>':'')+'<div class="choice-grid">'+choices+'</div>';nextButton.disabled=!isAnswered(step);nextButton.innerHTML=state.current===totalSteps-1?'Show my clarity snapshot <span>→</span>':'Continue <span>→</span>';previousButton.disabled=state.current===0}
area.addEventListener('input',event=>{const input=event.target.closest('[data-contact]');if(!input)return;state.contact[input.dataset.contact]=input.value;nextButton.disabled=!isAnswered(auditSteps[state.current])});area.addEventListener('click',event=>{const button=event.target.closest('.choice');if(!button)return;const step=auditSteps[state.current],answer=button.dataset.answer;if(step.multi){const selected=Array.isArray(state.answers[state.current])?[...state.answers[state.current]]:[],index=selected.indexOf(answer);if(index===-1)selected.push(answer);else selected.splice(index,1);state.answers[state.current]=selected}else state.answers[state.current]=answer;renderStep()});
nextButton.addEventListener('click',()=>{if(!isAnswered(auditSteps[state.current]))return;if(state.current===totalSteps-1){showResult();return}state.current+=1;renderStep()});previousButton.addEventListener('click',()=>{if(state.current>0){state.current-=1;renderStep()}});
function readinessNote(readiness,frequency){return readiness==='It mostly lives in my head'||readiness==='It changes each time'?'Because the process is still evolving and happens '+frequency.toLowerCase()+', start by making the useful steps visible before connecting anything.':'Because this work already has a repeatable shape and happens '+frequency.toLowerCase()+', you are well placed to simplify and automate the right handoffs.'}
function showResult(){const friction=state.answers[2],readiness=state.answers[3],frequency=state.answers[4],tools=state.answers[5],capacity=state.answers[6],outcome=state.answers[7],plan=recommendations[friction],toolList=tools.slice(0,2).join(' and '),product=productRecommendations[friction],offer=product?'<div class="result-offer"><p>Recommended ready-to-use automation</p><strong>'+product.name+'</strong><span>From '+product.price+' · designed around the tools you already use</span><a href="'+product.url+'">View this automation →</a></div>':'<div class="result-offer"><p>Recommended next step</p><strong>Personalised Workflow Clarity Audit</strong><span>Get your top workflow opportunities and a tailored action plan.</span><a href="personalised-audit.html">Explore the €199 audit →</a></div>';headerStep.textContent='Your clarity snapshot';headerProgress.style.width='100%';document.querySelector('.audit-card').classList.add('result-card');area.innerHTML='<div class="result-symbol">✓</div><p class="eyebrow">Your next best move</p><h2>'+plan.title+'</h2><p class="question-description">Because you want <strong>'+outcome.toLowerCase()+'</strong>, '+plan.summary+' This is designed for '+capacity.toLowerCase()+'.</p><p class="result-context">'+readinessNote(readiness,frequency)+'</p><div class="result-list"><div><span>01</span><p><strong>'+plan.first+'</strong><small>'+plan.firstDetail+'</small></p></div><div><span>02</span><p><strong>'+plan.second+'</strong><small>'+plan.secondDetail+'</small></p></div><div><span>03</span><p><strong>Use the tools you already have</strong><small>Start with '+toolList+' as the foundation, rather than adding more software too soon.</small></p></div></div>'+offer;document.querySelector('.audit-actions').innerHTML='<a class="button" href="personalised-audit.html">Get a personalised audit · €199 <span>→</span></a><a class="text-link" href="https://calendly.com/marguerite-workflow-clarity" target="_blank" rel="noreferrer">Book a free suitability call <span>↗</span></a><a class="text-link result-back-link" href="automations.html">Browse all automations <span>→</span></a>'}
renderStep();
